version: "3.7"

services:
  rxpy-web:
    ipc: host
    image: rxpy-web/devel
    stop_signal: SIGINT
    labels:
      com.dnsdock.image: "rxpy"
      com.dnsdock.region: "mintel"
    ports:
      - "8080:8080"
    volumes:
      - .:/app/
    stdin_open: true
    tty: true
